[theme]
base = "light"
# Color principal (Botones, inputs activos)
primaryColor = "#1E3A8A"
# Color de fondo principal
backgroundColor = "#F8FAFC"
# Color de fondo secundario (Sidebar, widgets)
secondaryBackgroundColor = "#F1F5F9"
# Color del texto
textColor = "#1E293B"
font = "sans serif"
