[theme]
base = "light"
# Color principal (Botones, inputs activos)
primaryColor = "#073af4ff"

# Color de fondo secundario (Sidebar, widgets)
secondaryBackgroundColor = "#09afa1ff"
# Color del texto
textColor = "#151516"
font = "Arial, sans serif"
# Configuración del servidor para acceso remoto y recarga automática
[server]
runOnSave = true
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[browser]
gatherUsageStats = false
