[theme]
base = "light"
# Color principal (Botones, inputs activos)
primaryColor = "#076af4ff"

# Color de fondo secundario (Sidebar, widgets)
secondaryBackgroundColor = "#f6f20374"
# Color del texto
textColor = "#0943efff"
font = "sans serif"
