[theme]
base = "light"
#Color de los botones
primaryColor = "#106e7dff"
#backgroundColor = "rgba(8, 197, 245, 0.91)"
# color de los uploaders
secondaryBackgroundColor = "rgba(8, 197, 245, 0.91)"
#textColor = "#fafafa"
font = "arials"
fontSize = "12px"

