[theme]
base = "light"
# Color principal (Botones, inputs activos)
primaryColor = "#076af4ff"

# Color de fondo secundario (Sidebar, widgets)
secondaryBackgroundColor = "#77EAE0"
# Color del texto
textColor = "#02100F"
font = "Arial, sans serif"
